/**
 * دليل المنزلة والمطرية — Fast PWA Service Worker
 * Cache-first app shell + stale-while-revalidate public data.
 * Authenticated/private API responses are never shared through CacheStorage.
 */
try {
  importScripts('https://www.gstatic.com/firebasejs/9.23.0/firebase-app-compat.js');
  importScripts('https://www.gstatic.com/firebasejs/9.23.0/firebase-messaging-compat.js');
  firebase.initializeApp({apiKey:"AIzaSyCUGecmvBdf6b38UVIM9zcxhbbux7VSzM",authDomain:"elmanzla-7402a.firebaseapp.com",projectId:"elmanzla-7402a",storageBucket:"elmanzla-7402a.firebasestorage.app",messagingSenderId:"252271215500",appId:"1:252271215500:web:adc234e58f4ba455fdcca9",measurementId:"G-EY6TEPLGSK"});
  const messaging=firebase.messaging();
  messaging.onBackgroundMessage(payload=>{const title=payload.notification?.title||payload.data?.title||'دليل المنزلة والمطرية 🔔';const body=payload.notification?.body||payload.data?.body||payload.data?.message||'تنبيه جديد في دليل المنزلة والمطرية';const url=payload.data?.url||payload.data?.actionUrl||payload.notification?.click_action||'./';eventlessNotification(title,body,url,payload)});
} catch(err){console.warn('[SW] Firebase messaging init warning:',err)}
const CACHE_VERSION='v4.5.0-ultrafast-mobile';
const STATIC_CACHE='manzala-static-'+CACHE_VERSION;
const DYNAMIC_CACHE='manzala-dynamic-'+CACHE_VERSION;
const IMAGE_CACHE='manzala-images-'+CACHE_VERSION;
const API_CACHE='manzala-api-'+CACHE_VERSION;
const STATIC_ASSETS=['./offline.html','./index.html','./places.html','./categories.html','./offers.html','./now.html','./around-me.html','./favorites.html','./search.html','./dashboard.html','./login.html','./contact.html','./place.html','./src/css/main.css','./src/css/islamic-hub.css','./src/css/pwa-install.css','./src/js/core/page-shell.js','./src/js/core/pwa-install.js','./src/js/ui/pages/islamic-hub.js','./manifest.webmanifest','/icons/icon-48x48.png','/icons/icon-72x72.png','/icons/icon-96x96.png','/icons/icon-192x192.png','/icons/icon-maskable-192x192.png','/icons/icon-512x512.png','/icons/icon-maskable-512x512.png','/favicon-48x48.png'];
const OFFLINE_PAGE='./offline.html';
self.addEventListener('install',event=>{event.waitUntil(caches.open(STATIC_CACHE).then(async cache=>{await Promise.all(STATIC_ASSETS.map(async asset=>{try{const res=await fetch(asset,{cache:'no-store'});if(res.ok)await cache.put(asset,res.clone())}catch(_){}}));}).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(k=>!k.startsWith('manzala-')||![STATIC_CACHE,DYNAMIC_CACHE,IMAGE_CACHE,API_CACHE].includes(k)).map(k=>caches.delete(k)))),self.clients.claim()]))});
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin===self.location.origin&&url.pathname.startsWith('/api/')){if(url.pathname.startsWith('/api/sync/')||request.headers.has('authorization')||request.credentials==='include'&&isPrivateApi(url.pathname))return;event.respondWith(staleWhileRevalidate(request,API_CACHE));return}if(url.hostname.includes('firebaseio.com')||url.hostname.includes('googleapis.com')||url.hostname.includes('identitytoolkit')||url.hostname.includes('gstatic.com')||url.hostname.includes('workers.dev'))return;if(isImageRequest(request,url)){event.respondWith(cacheFirstWithRefresh(request,IMAGE_CACHE));return}if(request.mode==='navigate'||request.headers.get('accept')?.includes('text/html')){event.respondWith(cacheFirstWithRefresh(request,DYNAMIC_CACHE,true));return}if(url.origin===self.location.origin&&url.pathname.match(/\.(js|css)$/i)){event.respondWith(cacheFirstWithRefresh(request,STATIC_CACHE));return}event.respondWith(cacheFirstWithRefresh(request,STATIC_CACHE))});
function isPrivateApi(path){return /\/(user|users|me|dashboard|notifications|favorites|owner|admin|auth|fcm|token)(\/|$)/i.test(path)}
function isImageRequest(request,url){return url.hostname.includes('r2.dev')||/\.(webp|jpg|jpeg|png|gif|svg|avif|ico)$/i.test(url.pathname)}
async function cacheFirstWithRefresh(request,cacheName,navigation=false){const cache=await caches.open(cacheName);const cached=await cache.match(request)||await cache.match(new Request(new URL(request.url).pathname,{method:'GET'}));const refresh=fetch(request).then(async res=>{if(res?.ok){try{await cache.put(request,res.clone())}catch(_){}}return res}).catch(()=>null);if(cached){eventually(refresh);return cached}const fresh=await refresh;if(fresh)return fresh;if(navigation){const offline=await caches.match(OFFLINE_PAGE);if(offline)return offline}return new Response('',{status:503,statusText:'Offline'})}
function eventually(p){p.catch(()=>{})}
async function staleWhileRevalidate(request,cacheName){const cache=await caches.open(cacheName);const cached=await cache.match(request);const refresh=fetch(request).then(async res=>{if(res?.ok){try{await cache.put(request,res.clone())}catch(_){}}return res}).catch(()=>null);if(cached){eventually(refresh);return cached}const fresh=await refresh;return fresh||apiEmptyResponse(request)}
function apiEmptyResponse(request){const path=new URL(request.url).pathname;let data=[];if(path==='/api/categories')data=[];return new Response(JSON.stringify({success:true,data}),{status:200,headers:{'Content-Type':'application/json;charset=utf-8','Cache-Control':'no-store'}})}
function eventlessNotification(title,body,url,payload){return self.registration.showNotification(title,{body,icon:payload.notification?.icon||payload.data?.icon||'./icons/icon-192x192.png',badge:'./icons/icon-96x96.png',dir:'rtl',lang:'ar',vibrate:[200,100,200],tag:payload.data?.tag||('fcm-bg-'+Date.now()),renotify:true,data:{url,timestamp:Date.now()}})}
self.addEventListener('push',event=>{let data={};try{data=event.data?event.data.json():{}}catch(_){data={message:event.data?.text?.()||''}}const title=data.notification?.title||data.data?.title||data.title||'دليل المنزلة والمطرية 🔔';const body=data.notification?.body||data.data?.body||data.data?.message||data.message||data.body||'لديك تنبيه جديد في دليل المنزلة والمطرية';const url=data.data?.url||data.data?.actionUrl||data.url||data.notification?.click_action||'./';event.waitUntil(self.registration.showNotification(title,{body,icon:data.notification?.icon||data.data?.icon||data.icon||'./icons/icon-192x192.png',badge:'./icons/icon-96x96.png',dir:'rtl',lang:'ar',vibrate:[200,100,200],tag:data.tag||data.data?.tag||('manzala-pwa-push-'+Date.now()),renotify:true,data:{url,timestamp:Date.now()}}));event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(cs=>cs.forEach(c=>c.postMessage({type:'DATA_VERSION_CHANGED',payload:{timestamp:Date.now()}}))))});
self.addEventListener('notificationclick',event=>{event.notification.close();const targetUrl=event.notification.data?.url||'./';event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(cs=>{for(const client of cs){if('focus' in client){client.focus();if('navigate' in client&&targetUrl)client.navigate(targetUrl);return}}return clients.openWindow?clients.openWindow(targetUrl):undefined}))});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='INVALIDATE_API_CACHE'||event.data?.type==='DATA_VERSION_CHANGED')caches.delete(API_CACHE).catch(()=>{});if(event.data?.type==='SHOW_PWA_NOTIFICATION'){const n=event.data.payload||{};event.waitUntil(self.registration.showNotification(n.title||'دليل المنزلة والمطرية 🔔',{body:n.message||n.body||'',icon:n.icon||'./icons/icon-192x192.png',badge:'./icons/icon-96x96.png',dir:'rtl',lang:'ar',vibrate:[150,50,150,50,200],tag:n.tag||'pwa-local-push-'+Date.now(),renotify:true,data:{url:n.url||n.actionUrl||'./'}}))}});
