import { api } from '../core/api.js';
import { setCurrentAdminRole } from '../core/auth.js';
export const AdminService={
 getDashboard:async()=>{const r=await api.get('/api/admin/dashboard');if(r?.data?.admin?.role)setCurrentAdminRole(r.data.admin.role);return r.data},
 getPlaces:(p={})=>api.get('/api/admin/places',p),getPlace:id=>api.get('/api/admin/places/'+encodeURIComponent(id)).then(r=>r.data),createPlace:b=>api.post('/api/admin/places',b).then(r=>r.data),updatePlace:(id,b)=>api.put('/api/admin/places/'+encodeURIComponent(id),b).then(r=>r.data),deletePlace:id=>api.delete('/api/admin/places/'+encodeURIComponent(id)),verifyPlace:(id,v,notes='')=>api.patch('/api/admin/places/'+encodeURIComponent(id)+'/verify',{is_verified:v?1:0,notes}),publishPlace:(id,v)=>api.patch('/api/admin/places/'+encodeURIComponent(id)+'/status',{status:v?'published':'pending'}),updatePlaceStatus:(id,status)=>api.patch('/api/admin/places/'+encodeURIComponent(id)+'/status',{status}),bulkPlacesAction:(action,ids)=>api.post('/api/admin/places/bulk',{action,ids}),
 getUsers:p=>api.get('/api/admin/users',p),updateUserRole:(id,role)=>api.put('/api/admin/users/'+encodeURIComponent(id)+'/role',{role}),updateUserStatus:(id,status,reason='')=>api.post('/api/admin/users/'+encodeURIComponent(id)+'/status',{status,reason}),
 getVerificationQueue:p=>api.get('/api/admin/verification-queue',p),decideVerification:(id,decision,notes='')=>api.post('/api/admin/verification-queue/'+encodeURIComponent(id)+'/decide',{decision,notes}),
 getCategories:()=>api.get('/api/admin/categories').then(r=>r.data),saveCategory:b=>api.put('/api/admin/categories',b).then(r=>r.data),deleteCategory:id=>api.delete('/api/admin/categories/'+encodeURIComponent(id)),reorderCategories:o=>api.put('/api/admin/categories/reorder',{order:o}),
 getReviews:p=>api.get('/api/admin/reviews',p),deleteReview:id=>api.delete('/api/admin/reviews/'+encodeURIComponent(id)),getProducts:p=>api.get('/api/admin/products',p),moderateProduct:(id,status,notes='')=>api.put('/api/admin/products/'+encodeURIComponent(id)+'/moderate',{status,notes}),
 getMediaList:p=>api.get('/api/admin/media',p),deleteMedia:key=>api.delete('/api/admin/media',{key}),uploadMedia:(file,folder='uploads')=>{const f=new FormData();f.append('file',file);f.append('folder',folder);return api.post('/api/upload',f)},
 getAuditLogs:p=>api.get('/api/admin/audit-logs',p),getSystemHealth:()=>api.get('/api/admin/system-health').then(r=>r.data),globalSearch:q=>api.get('/api/admin/search',{q}).then(r=>r.data),getBannedIps:()=>api.get('/api/admin/security/bans').then(r=>r.data),banIp:(ip,reason='',expiresAt=null)=>api.post('/api/admin/security/bans',{ip,reason,expiresAt}),unbanIp:ip=>api.delete('/api/admin/security/bans/'+encodeURIComponent(ip)),sendNotification:b=>api.post('/api/admin/notifications/send',b)
};
