/* Universal PWA install prompt for every page shell. */
let deferredPrompt=null,banner=null,showTimer=null;
function loadPwaStyles(){if(document.getElementById('pwa-install-design'))return;const link=document.createElement('link');link.id='pwa-install-design';link.rel='stylesheet';link.href='/src/css/pwa-install.css?v=20260913.2';document.head.appendChild(link);}
function isEnglish(){return document.documentElement.lang==='en'||location.pathname==='/en'||location.pathname.startsWith('/en/');}
function isStandalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true||document.referrer.includes('android-app://');}
function ensureBanner(){if(isStandalone())return null;if(document.getElementById('pwa-banner'))return document.getElementById('pwa-banner');const en=isEnglish(),slot=document.getElementById('pwa-slot')||document.body;banner=document.createElement('aside');banner.id='pwa-banner';banner.className='pwa-banner';banner.hidden=true;banner.setAttribute('role','dialog');banner.setAttribute('aria-label',en?'Install app':'تثبيت التطبيق');banner.innerHTML=`<div class="pwa-banner__content"><div class="pwa-banner__icon">📱</div><div class="pwa-banner__text"><strong class="pwa-banner__title">${en?'Install Dalil El Manzala & El Matariya':'ثبّت دليل المنزلة والمطرية'}</strong><span class="pwa-banner__desc">${en?'Install the app for faster access and a better experience.':'ثبّت التطبيق للوصول السريع وتجربة أفضل.'}</span></div></div><div class="pwa-banner__actions"><button class="btn btn-primary btn-sm" id="pwa-install-btn" type="button">${en?'Install App':'تثبيت التطبيق'}</button><button class="pwa-banner__close" id="pwa-banner-close" type="button" aria-label="${en?'Close':'إغلاق'}">✕</button></div>`;slot.appendChild(banner);banner.querySelector('#pwa-install-btn')?.addEventListener('click',async()=>{if(!deferredPrompt){showManualInstructions();return;}try{deferredPrompt.prompt();const choice=await deferredPrompt.userChoice;if(choice?.outcome==='accepted'){deferredPrompt=null;hideBanner();}}catch(_){}});banner.querySelector('#pwa-banner-close')?.addEventListener('click',()=>{hideBanner();try{sessionStorage.setItem('pwa-banner-dismissed','1');}catch(_){}});return banner;}
function showBanner(force=false){const b=ensureBanner();if(!b||isStandalone())return;let dismissed=false;try{dismissed=sessionStorage.getItem('pwa-banner-dismissed')==='1';}catch(_){}if(!force&&dismissed)return;b.hidden=false;requestAnimationFrame(()=>b.classList.add('visible'));}
function hideBanner(){const b=document.getElementById('pwa-banner');if(!b)return;b.classList.remove('visible');setTimeout(()=>{b.hidden=true;},350);}
function showManualInstructions(){const en=isEnglish(),ios=/iphone|ipad|ipod/i.test(navigator.userAgent),message=en?(ios?'On iPhone or iPad, tap Share, then choose “Add to Home Screen”.':'Open the browser menu and choose “Install app” or “Add to Home screen”.'):(ios?'على iPhone أو iPad: اضغط مشاركة ثم اختر «إضافة إلى الشاشة الرئيسية».':'افتح قائمة المتصفح واختر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية».');window.alert(message);}
function scheduleFallbackBanner(){clearTimeout(showTimer);showTimer=setTimeout(()=>showBanner(false),1600);}
function capture(e){e.preventDefault();deferredPrompt=e;window.__deferredPwaPrompt=e;clearTimeout(showTimer);setTimeout(()=>showBanner(false),400);}
window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',()=>{deferredPrompt=null;window.__deferredPwaPrompt=null;clearTimeout(showTimer);hideBanner();});if(window.__deferredPwaPrompt){deferredPrompt=window.__deferredPwaPrompt;setTimeout(()=>showBanner(false),400);}
async function ensureServiceWorker(){if(!('serviceWorker' in navigator))return null;try{const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/'});await registration.update().catch(()=>{});if(registration.waiting)registration.waiting.postMessage({type:'SKIP_WAITING'});return registration;}catch(err){console.warn('[PWA] Service worker registration:',err);return null;}}
async function refreshPwaRuntime(){try{const registration=await ensureServiceWorker();if(registration){registration.update().catch(()=>{});if(registration.waiting)registration.waiting.postMessage({type:'SKIP_WAITING'});}}catch(_){} }
function bootPwaInstall(){loadPwaStyles();ensureBanner();scheduleFallbackBanner();refreshPwaRuntime();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootPwaInstall,{once:true});else bootPwaInstall();
