/* Universal PWA install prompt + mobile shell utilities. */
let deferredPrompt=null,banner=null,showTimer=null;
function loadPwaStyles(){if(document.getElementById('pwa-install-design'))return;const link=document.createElement('link');link.id='pwa-install-design';link.rel='stylesheet';link.href='/src/css/pwa-install.css?v=a58f9ed6';document.head.appendChild(link);}
function isEnglish(){return document.documentElement.lang==='en'||location.pathname==='/en'||location.pathname.startsWith('/en/');}
function isStandalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true||document.referrer.includes('android-app://');}
function ensureBanner(){if(isStandalone())return null;if(document.getElementById('pwa-banner'))return document.getElementById('pwa-banner');const en=isEnglish(),slot=document.getElementById('pwa-slot')||document.body;banner=document.createElement('div');banner.id='pwa-banner';banner.className='pwa-banner';banner.hidden=true;banner.setAttribute('role','dialog');banner.setAttribute('aria-label',en?'Install app':'تثبيت التطبيق');banner.innerHTML=`<div class="pwa-banner__content"><div class="pwa-banner__icon">📱</div><div class="pwa-banner__text"><strong class="pwa-banner__title">${en?'Install Dalil El Manzala & El Matariya':'ثبّت دليل المنزلة والمطرية'}</strong><span class="pwa-banner__desc">${en?'Install the app for faster access and a better experience.':'ثبّت التطبيق للوصول السريع وتجربة أفضل.'}</span></div></div><div class="pwa-banner__actions"><button class="btn btn-primary btn-sm" id="pwa-install-btn" type="button">${en?'Install App':'تثبيت التطبيق'}</button><button class="pwa-banner__close" id="pwa-banner-close" type="button" aria-label="${en?'Close':'إغلاق'}">✕</button></div>`;slot.appendChild(banner);banner.querySelector('#pwa-install-btn')?.addEventListener('click',async()=>{if(!deferredPrompt){showManualInstructions();return;}try{deferredPrompt.prompt();const choice=await deferredPrompt.userChoice;if(choice?.outcome==='accepted'){deferredPrompt=null;hideBanner();}}catch(_){}});banner.querySelector('#pwa-banner-close')?.addEventListener('click',()=>{hideBanner();try{sessionStorage.setItem('pwa-banner-dismissed','1');}catch(_){}});return banner;}
function showBanner(force=false){const b=ensureBanner();if(!b||isStandalone())return;let dismissed=false;try{dismissed=sessionStorage.getItem('pwa-banner-dismissed')==='1';}catch(_){}if(!force&&dismissed)return;b.hidden=false;requestAnimationFrame(()=>b.classList.add('visible'));}
function hideBanner(){const b=document.getElementById('pwa-banner');if(!b)return;b.classList.remove('visible');setTimeout(()=>{b.hidden=true;},350);}
function showManualInstructions(){const en=isEnglish(),ios=/iphone|ipad|ipod/i.test(navigator.userAgent),message=en?(ios?'On iPhone or iPad, tap Share, then choose “Add to Home Screen”.':'Open the browser menu and choose “Install app” or “Add to Home screen”.'):(ios?'على iPhone أو iPad: اضغط مشاركة ثم اختر «إضافة إلى الشاشة الرئيسية».':'افتح قائمة المتصفح واختر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية».');window.alert(message);}
function scheduleFallbackBanner(){clearTimeout(showTimer);showTimer=setTimeout(()=>showBanner(false),1600);}
function capture(e){e.preventDefault();deferredPrompt=e;window.__deferredPwaPrompt=e;clearTimeout(showTimer);setTimeout(()=>showBanner(false),400)}
window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',()=>{deferredPrompt=null;window.__deferredPwaPrompt=null;clearTimeout(showTimer);hideBanner()});if(window.__deferredPwaPrompt){deferredPrompt=window.__deferredPwaPrompt;setTimeout(()=>showBanner(false),400)}
async function ensureServiceWorker(){if(!('serviceWorker' in navigator))return null;try{const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/'});if(registration.update)registration.update().catch(()=>{});if(registration.waiting)registration.waiting.postMessage({type:'SKIP_WAITING'});return registration}catch(err){console.warn('[PWA] Service worker registration:',err);return null}}
function installDesktopDisplayRail(){if(window.innerWidth<1024||document.getElementById('display-controls-rail'))return;const lang=document.getElementById('lang-toggle-btn'),theme=document.getElementById('theme-toggle-btn');if(!lang&&!theme)return;const rail=document.createElement('aside');rail.id='display-controls-rail';rail.className='display-controls-rail';rail.setAttribute('aria-label',isEnglish()?'Language and theme controls':'عناصر التحكم في اللغة والمظهر');if(theme)rail.appendChild(theme);if(lang)rail.appendChild(lang);document.body.appendChild(rail)}
async function refreshPwaRuntime(){try{const registration=await ensureServiceWorker();if(registration){registration.update().catch(()=>{});if(registration.waiting)registration.waiting.postMessage({type:'SKIP_WAITING'})}}catch(_){} }
const DASHBOARD_MOBILE_LINKS_AR=[['🏠','نظرة عامة','/dashboard.html'],['📍','أماكني','/dashboard.html?section=places'],['📈','التقارير والإحصائيات','/dashboard.html?section=analytics'],['⭐','متابعاتي وعروضها','/dashboard.html?section=following'],['🗺️','بالقرب مني (GPS)','/dashboard.html?section=around-me'],['🎁','نادي الولاء والنقاط','/dashboard.html?section=loyalty'],['📸','تصوير كارت المحل (AI)','/dashboard.html?section=add&action=scan'],['➕','إضافة مكان يدويًا','/dashboard.html?section=add'],['🔔','الإشعارات والزيارات','/dashboard.html?section=notifications'],['🛡️','وثق ملفك (العلامة الزرقاء)','/contact.html?type=verification']];
const DASHBOARD_MOBILE_LINKS_EN=[['🏠','Overview','/en/dashboard/'],['📍','My Places','/en/dashboard/?section=places'],['📈','Reports & Analytics','/en/dashboard/?section=analytics'],['⭐','Following & Offers','/en/dashboard/?section=following'],['🗺️','Near Me (GPS)','/en/dashboard/?section=around-me'],['🎁','Loyalty & Points','/en/dashboard/?section=loyalty'],['📸','Business Card AI','/en/dashboard/?section=add&action=scan'],['➕','Add a Place','/en/dashboard/?section=add'],['🔔','Notifications','/en/dashboard/?section=notifications'],['🛡️','Verify Your Profile','/en/contact/?type=verification']];
function currentAuthUser(){try{return window.firebase?.auth?.().currentUser||null}catch(_){return null}}
async function isCurrentUserAdmin(user){if(!user)return false;try{const mod=await import('./auth.js');return !!mod.isAdmin(mod.getCurrentUser?.()||user)}catch(_){try{const token=await user.getIdTokenResult();return !!(token.claims?.admin||token.claims?.role==='admin'||token.claims?.role==='superadmin')}catch(_){return false}}}
async function syncMobileMoreMenu(){const sheet=document.getElementById('mobile-more-sheet');if(!sheet)return;const links=sheet.querySelector('[data-more-links]');if(!links)return;const user=currentAuthUser();const en=isEnglish();const base=en?[['🏠','Home','/en/'],['📍','Places Directory','/en/places/'],['📋','Categories','/en/categories/'],['🏷️','Offers','/en/offers/'],['❤️','Favorites','/en/favorites/']]:[['🏠','الرئيسية','/index.html'],['📍','دليل الأماكن','/places.html'],['📋','التصنيفات','/categories.html'],['🏷️','العروض','/offers.html'],['❤️','المفضلة','/favorites.html']];if(!user){links.innerHTML=base.map(([i,t,h])=>`<a class="mobile-more-sheet__link" href="${h}"><span>${i} ${t}</span><span aria-hidden="true">›</span></a>`).join('');return}const dash=en?DASHBOARD_MOBILE_LINKS_EN:DASHBOARD_MOBILE_LINKS_AR;const publicLinks=en?[['🔎','Search Directory','/en/search/'],['🤝','Community Requests','/en/now/'],['✉️','Contact Us','/en/contact/']]:[['🔎','البحث في الدليل','/search.html'],['🤝','طلبات أهالينا','/now.html'],['✉️','تواصل معنا','/contact.html']];let html=`<div class="mobile-more-sheet__section-title">${en?'My Dashboard':'لوحة تحكمي'}</div>`+dash.map(([i,t,h])=>`<a class="mobile-more-sheet__link mobile-more-sheet__dashboard-link" href="${h}"><span>${i} ${t}</span><span aria-hidden="true">›</span></a>`).join('')+`<div class="mobile-more-sheet__section-title">${en?'Directory':'الدليل'}</div>`+base.concat(publicLinks).map(([i,t,h])=>`<a class="mobile-more-sheet__link" href="${h}"><span>${i} ${t}</span><span aria-hidden="true">›</span></a>`).join('');if(await isCurrentUserAdmin(user))html+=`<div class="mobile-more-sheet__section-title">${en?'Administration':'الإدارة'}</div><a class="mobile-more-sheet__link mobile-more-sheet__admin-link" href="/admin/index.html"><span>⚙️ ${en?'Admin Dashboard':'لوحة تحكم الإدارة'}</span><span aria-hidden="true">›</span></a>`;links.innerHTML=html}
function observeAuthenticatedMoreMenu(){if(document.body.dataset.authMoreObserver==='1')return;document.body.dataset.authMoreObserver='1';const observer=new MutationObserver(()=>{if(document.getElementById('mobile-more-sheet'))syncMobileMoreMenu().catch(()=>{})});observer.observe(document.body,{childList:true,subtree:true});const bind=()=>{try{const auth=window.firebase?.auth?.();if(auth){auth.onAuthStateChanged(()=>syncMobileMoreMenu().catch(()=>{}));syncMobileMoreMenu().catch(()=>{})}}catch(_){} };setTimeout(bind,500);setTimeout(bind,2000)}
function ensureMobileActionHints(){if(window.innerWidth>767||document.getElementById('mobile-action-hints'))return;const wrap=document.createElement('div');wrap.id='mobile-action-hints';wrap.className='mobile-action-hints';const en=isEnglish();wrap.innerHTML=`<button type="button" class="mobile-action-hint mobile-action-hint--voice" data-action="voice"><span class="mobile-action-hint__icon">🎙️</span><span>${en?'Search by voice':'ابحث بصوتك'}</span></button><a class="mobile-action-hint mobile-action-hint--add" href="${en?'/en/dashboard/?section=add':'/dashboard.html?section=add'}"><span class="mobile-action-hint__icon">➕</span><span>${en?'Add your place':'أضف مكانك من هنا'}</span></a>`;document.body.appendChild(wrap);wrap.querySelector('[data-action="voice"]')?.addEventListener('click',()=>document.getElementById('global-voice-assistant-fab')?.click());const update=()=>{const isAdd=/dashboard\.html|\/dashboard\//.test(location.pathname)&&new URLSearchParams(location.search).get('section')==='add';wrap.querySelector('.mobile-action-hint--add')?.classList.toggle('is-hidden',isAdd)};update();window.addEventListener('popstate',update);setInterval(update,1500)}
async function restorePwaNotificationPrompt(){if(!isStandalone()||typeof Notification==='undefined'||Notification.permission!=='default')return;try{localStorage.removeItem('manzala_push_dismissed');const mod=await import('../services/fcm.service.js');mod.mountPushNotificationPrompt?.(currentAuthUser());}catch(_){} }
function bootPwaInstall(){loadPwaStyles();ensureBanner();scheduleFallbackBanner();refreshPwaRuntime();setTimeout(installDesktopDisplayRail,300);observeAuthenticatedMoreMenu();setTimeout(ensureMobileActionHints,900);setTimeout(restorePwaNotificationPrompt,1100);window.addEventListener('resize',()=>{if(window.innerWidth>=1024)installDesktopDisplayRail();if(window.innerWidth>767)document.getElementById('mobile-action-hints')?.remove();else ensureMobileActionHints()},{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootPwaInstall,{once:true});else bootPwaInstall();
