import { getPlacesByOwner } from '../../core/db.js';
import { getArticles, generateArticle, saveArticle, updateArticle, deleteArticle, uploadArticleCover } from '../../services/articles.service.js';
import { toast } from './Toast.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function styles(){
 if(document.getElementById('article-manager-styles'))return;
 const s=document.createElement('style');s.id='article-manager-styles';s.textContent='.article-manager{display:grid;gap:18px}.article-manager__head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.article-manager__stats{display:flex;gap:8px;flex-wrap:wrap}.article-manager__stat{padding:8px 12px;border:1px solid #dbe4ea;border-radius:999px;background:#fff;font-weight:800;font-size:12px}.article-editor{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:18px}@media(max-width:900px){.article-editor{grid-template-columns:1fr}}.article-panel{background:var(--surface,#fff);border:1px solid #e2e8f0;border-radius:18px;padding:18px;box-shadow:0 6px 22px rgba(15,23,42,.05)}.article-field{display:grid;gap:7px;margin-bottom:14px}.article-field label{font-weight:800;font-size:13px;color:#0f172a}.article-field input,.article-field textarea,.article-field select{width:100%;box-sizing:border-box;border:1px solid #d7e0e8;border-radius:12px;padding:11px 12px;font:inherit;background:#fff;color:#0f172a}.article-field textarea{min-height:180px;resize:vertical;line-height:1.9}.article-topic{min-height:90px}.article-actions{display:flex;gap:8px;flex-wrap:wrap}.article-list{display:grid;gap:12px}.article-mini{border:1px solid #e2e8f0;border-radius:14px;overflow:hidden;background:#fff}.article-mini img{width:100%;aspect-ratio:16/9;object-fit:cover;display:block;background:#eef2f7}.article-mini__body{padding:12px}.article-mini h3{margin:0 0 6px;font-size:14px;line-height:1.6}.article-mini p{margin:0 0 10px;font-size:12px;color:#64748b;line-height:1.7}.article-progress{font-size:12px;color:#64748b}.article-cover-preview{width:100%;aspect-ratio:16/9;border-radius:12px;object-fit:cover;background:#eef2f7;display:block;margin-top:8px}';document.head.appendChild(s);
}

export async function renderArticlesManager(container,user){
 styles();
 let places=[];let currentPlace='';let articles=[];let editing=null;
 container.innerHTML='<div class="article-manager"><div class="article-manager__head"><div><h1 class="dashboard-header__title">📝 المدونة والمقالات</h1><p class="dashboard-header__subtitle">اكتب محتوى مفيدًا عن نشاطك، ولّد مسودة بالذكاء الاصطناعي ثم راجعها قبل النشر.</p></div><div class="article-manager__stats"><span class="article-manager__stat" id="article-count-stat">0 / 6 مقالات</span></div></div><div id="article-manager-body"></div></div>';
 const body=container.querySelector('#article-manager-body');
 try{places=await getPlacesByOwner(user)||[]}catch(_){places=[]}
 if(!places.length){body.innerHTML='<div class="empty-state"><div class="empty-state__icon">🏪</div><h2>لا توجد أماكن مرتبطة بحسابك</h2><p>أضف مكانًا أولاً ثم ستظهر هنا أدوات المقالات.</p></div>';return}
 currentPlace=places[0].id||places[0]._key;
 async function load(){articles=await getArticles({placeId:currentPlace,limit:6}).catch(()=>[]);editing=null;render()}
 function render(){
  const stat=document.getElementById('article-count-stat');if(stat)stat.textContent=`${articles.length} / 6 مقالات`;
  body.innerHTML=`<div class="article-editor"><section class="article-panel"><div class="article-field"><label>المكان</label><select id="article-place">${places.map(p=>{const id=p.id||p._key;return `<option value="${esc(id)}" ${String(id)===String(currentPlace)?'selected':''}>${esc(p.name||'مكان')}</option>`}).join('')}</select></div><div class="article-field"><label>عن ماذا تريد أن تتحدث المقالة؟</label><textarea id="article-topic" class="article-topic" placeholder="مثال: خدمات صيانة الأجهزة الكهربائية ومتى يحتاج العميل إلى فني متخصص."></textarea></div><div class="article-field"><label>عنوان مقترح (اختياري)</label><input id="article-title" maxlength="180" placeholder="عنوان المقال" value="${esc(editing?.title||'')}"></div><div class="article-field"><label>الكلمات المفتاحية (اختياري)</label><input id="article-keywords" placeholder="افصل بين الكلمات بفواصل" value="${esc((editing?.keywords||[]).join(', '))}"></div><div class="article-actions"><button type="button" class="btn btn-primary" id="article-generate">✨ توليد المقال بالذكاء الاصطناعي</button><button type="button" class="btn btn-outline" id="article-clear">مسح</button></div><div class="article-field" style="margin-top:16px"><label>نص المقال</label><textarea id="article-content" maxlength="700" placeholder="ستظهر هنا المسودة بعد التوليد أو اكتبها بنفسك">${esc(editing?.content||'')}</textarea><div class="article-progress" id="article-progress">${editing?.content?`${editing.content.length} حرف`:'الهدف: حوالي 500 حرف'}</div></div><div class="article-field"><label>صورة المقال</label><input id="article-cover" type="file" accept="image/jpeg,image/png,image/webp"><img id="article-cover-preview" class="article-cover-preview" alt="معاينة صورة المقال" style="${editing?.coverImageUrl?'':'display:none'}" src="${esc(editing?.coverImageUrl||'')}"></div><div class="article-actions"><button type="button" class="btn btn-outline" id="article-draft">💾 حفظ كمسودة</button><button type="button" class="btn btn-primary" id="article-publish">🚀 نشر المقال</button></div></section><aside class="article-panel"><h2 style="margin:0 0 12px;font-size:16px;font-weight:900">مقالات هذا المكان</h2><p style="margin:0 0 14px;color:#64748b;font-size:12px;line-height:1.7">حد أقصى 6 مقالات لكل مكان.</p><div class="article-list">${articles.map(a=>`<article class="article-mini">${a.coverImageUrl?`<img src="${esc(a.coverImageUrl)}" alt="${esc(a.title)}">`:'<div style="aspect-ratio:16/9;background:#eef2f7;display:grid;place-items:center;font-size:36px">📝</div>'}<div class="article-mini__body"><h3>${esc(a.title)}</h3><p>${esc(a.excerpt||a.content?.slice(0,120)||'')}</p><div class="article-actions"><button type="button" class="btn btn-sm btn-outline" data-edit="${esc(a.id)}">تعديل</button><button type="button" class="btn btn-sm btn-outline" data-delete="${esc(a.id)}">حذف</button></div></div></article>`).join('')}</div></aside></div>`;
  const placeSelect=body.querySelector('#article-place');placeSelect.addEventListener('change',e=>{currentPlace=e.target.value;load()});
  body.querySelector('#article-content').addEventListener('input',e=>{body.querySelector('#article-progress').textContent=`${e.target.value.length} حرف — الهدف حوالي 500 حرف`});
  body.querySelector('#article-clear').addEventListener('click',()=>{editing=null;render()});
  body.querySelector('#article-generate').addEventListener('click',async()=>{const topic=body.querySelector('#article-topic').value.trim();if(!topic){toast.error?.('اكتب أولاً ما تريد أن تتحدث عنه المقالة');return}const btn=body.querySelector('#article-generate');btn.disabled=true;btn.textContent='⏳ جاري توليد المقال...';try{const d=await generateArticle({placeId:currentPlace,topic,title:body.querySelector('#article-title').value.trim(),keywords:body.querySelector('#article-keywords').value.split(',').map(v=>v.trim()).filter(Boolean)});body.querySelector('#article-title').value=d.title||'';body.querySelector('#article-keywords').value=(d.keywords||[]).join(', ');body.querySelector('#article-content').value=d.content||'';body.querySelector('#article-progress').textContent=`${(d.content||'').length} حرف — راجع المقال قبل النشر`;}catch(err){toast.error?.(err.message||'تعذر توليد المقال')}finally{btn.disabled=false;btn.textContent='✨ توليد المقال بالذكاء الاصطناعي'}});
  async function persist(draft){const title=body.querySelector('#article-title').value.trim();const articleText=body.querySelector('#article-content').value.trim();if(!title||!articleText){toast.error?.('أكمل العنوان والمحتوى أولاً');return}const file=body.querySelector('#article-cover').files?.[0];let cover=editing?.coverImageUrl||'';if(file){try{cover=await uploadArticleCover(file,editing?.slug||title)}catch(err){toast.error?.(err.message||'تعذر رفع صورة المقال');return}}const payload={id:editing?.id,placeId:currentPlace,title,content:articleText,excerpt:articleText.slice(0,180),keywords:body.querySelector('#article-keywords').value.split(',').map(v=>v.trim()).filter(Boolean),coverImageUrl:cover,ai_generated:Boolean(editing?.aiGenerated)};try{if(editing)await updateArticle(editing.id,payload,{draft});else await saveArticle(payload,{draft});toast.success?.(draft?'تم حفظ المسودة':'تم نشر المقال');await load()}catch(err){toast.error?.(err.message||'تعذر حفظ المقال')}}
  body.querySelector('#article-draft').addEventListener('click',()=>persist(true));body.querySelector('#article-publish').addEventListener('click',()=>persist(false));
  body.querySelectorAll('[data-edit]').forEach(btn=>btn.addEventListener('click',()=>{editing=articles.find(a=>String(a.id)===String(btn.dataset.edit))||null;render()}));
  body.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',async()=>{if(!confirm('حذف المقال؟'))return;try{await deleteArticle(btn.dataset.delete);toast.success?.('تم حذف المقال');await load()}catch(err){toast.error?.(err.message||'تعذر حذف المقال')}}));
  body.querySelector('#article-cover').addEventListener('change',e=>{const f=e.target.files?.[0];const img=body.querySelector('#article-cover-preview');if(!f){img.style.display=editing?.coverImageUrl?'block':'none';return}img.src=URL.createObjectURL(f);img.style.display='block'});
 }
 await load();
}