name = "elmanzala"
main = "index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "elmanzala"
bucket_name = "elmanzala"

[[d1_databases]]
binding = "DB"
database_name = "dalilmanzala-db"
database_id = "9e98b9d3-619f-4ef4-9af5-6458c2382251"

[vars]
OPENROUTER_API_KEY = "sk-or-v1-openrouter-free"