name = "elmanzala"
main = "index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "elmanzala"
bucket_name = "elmanzala"


[vars]
TURSO_DATABASE_URL = "https://dalilmanzala-mohamednasr.aws-eu-west-1.turso.io"
OPENROUTER_API_KEY = "sk-or-v1-openrouter-free"
FIREBASE_API_KEY = "AIzaSyCUGCecmvBdf6b38UVIM9zcxhbbux7VSzM"
[triggers]
crons = ["0 * * * *"]
