import { AdminService } from '../services/admin.service.js';
import { renderStatCard } from '../components/stat-card.js';
import { updateSidebarBadge } from '../components/sidebar.js';
import { toast } from '../components/toast.js';
import { can } from '../core/auth.js';

export async function renderOverviewPage(container){
 container.innerHTML=`<div class="admin-page-header"><div><h1 class="admin-page-title">لوحة التحكم والمؤشرات</h1><p class="admin-page-desc">أرقام حقيقية من Turso وحالة مباشرة للخدمات</p></div><div class="admin-page-actions"><button id="btn-refresh-overview" class="btn btn-secondary btn-sm">↻ تحديث</button>${can('places.create')?'<a href="#place-edit/new" class="btn btn-primary btn-sm">+ إضافة مكان</a>':''}</div></div><div class="admin-stats-grid" id="overview-stats-grid"></div><div class="admin-dashboard-row"><div class="admin-card card-half"><div class="admin-card-header"><h2 class="admin-card-title">🛡️ ما يحتاج إجراء</h2></div><div class="admin-card-body" id="overview-attention-body"></div></div><div class="admin-card card-half"><div class="admin-card-header"><h2 class="admin-card-title">🩺 حالة الخدمات</h2><a href="#system-health" class="btn btn-outline btn-xs">التفاصيل</a></div><div class="admin-card-body" id="overview-health-body"></div></div></div>`;
 container.querySelector('#btn-refresh-overview').onclick=()=>loadDashboardData(container);await loadDashboardData(container);
}
function val(obj,key){return obj&&obj.status==='ok'&&obj[key]!==undefined?Number(obj[key]):null}
function labelValue(v){return v===null?'غير متاح':v.toLocaleString('ar-EG')}
async function loadDashboardData(container){const grid=container.querySelector('#overview-stats-grid'),att=container.querySelector('#overview-attention-body'),health=container.querySelector('#overview-health-body');grid.innerHTML='';for(let i=0;i<6;i++)grid.appendChild(renderStatCard({isLoading:true}));try{const d=await AdminService.getDashboard();const m=d?.metrics||{};const cards=[['places-total','إجمالي الأماكن',val(m.places,'total'),'🏢'],['places-verified','الأماكن الموثقة',val(m.places,'verified'),'✓'],['verification-pending','طلبات التوثيق',val(m.verification,'pending'),'⏳'],['users-total','المستخدمون',val(m.users,'total'),'👥'],['reviews-total','التقييمات',val(m.reviews,'total'),'⭐'],['categories-total','التصنيفات',val(m.categories,'total'),'🗂️']];grid.innerHTML='';for(const [id,title,value,icon] of cards)grid.appendChild(renderStatCard({id,title,value:value===null?'غير متاح':value,icon,isError:value===null,errorMessage:'تعذر قراءة القيمة من Turso'}));const pv=val(m.verification,'pending'),pp=val(m.products,'pending'),pl=val(m.places,'pending');att.innerHTML=[['verification','طلبات توثيق',pv,'#verification'],['places','أماكن معلقة',pl,'#places'],['products','منتجات معلقة',pp,'#products']].filter(x=>x[2]!==null&&x[2]>0).map(x=>`<div class="attention-item"><div><strong>${x[2].toLocaleString('ar-EG')} ${x[1]}</strong></div><a href="${x[3]}" class="btn btn-sm btn-warning">مراجعة</a></div>`).join('')||'<div class="attention-all-clear">🎉 لا توجد إجراءات معلقة معروفة.</div>';const h=d?.health||{};health.innerHTML=Object.entries(h).map(([k,x])=>`<div class="health-mini-item"><span>${k}</span><span class="badge ${x?.status==='healthy'?'badge-success':'badge-warning'}">${x?.status||'غير متاح'}</span></div>`).join('');const pending=val(m.verification,'pending');if(pending!==null)updateSidebarBadge('badge-nav-verification',pending)}catch(e){toast.error(e.message||'تعذر قراءة Dashboard');grid.innerHTML='';for(const [id,title] of [['places-total','إجمالي الأماكن'],['places-verified','الأماكن الموثقة'],['verification-pending','طلبات التوثيق'],['users-total','المستخدمون'],['reviews-total','التقييمات'],['categories-total','التصنيفات']])grid.appendChild(renderStatCard({id,title,value:'غير متاح',isError:true,errorMessage:e.message||'تعذر الاتصال'}));att.innerHTML='<div class="alert alert-danger"><strong>تعذر قراءة قاعدة البيانات.</strong><p>'+escapeHtml(e.message||'خطأ غير معروف')+'</p></div>';health.innerHTML='<div class="alert alert-warning">حالة الخدمات غير مؤكدة.</div>'}}
function escapeHtml(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
